name : DebugBuild
on:
  push:
    branches:
      - master
      
env:
  # リポジトリのルートディレクトリを基点としたソリューションファイルのパス
  SOLUTION_FILE_PATH: C:\Users\k024g\OneDrive\デスクトップ\CG2\CG2_project\project\CG2_project.sln
  # Visual Studio の構成(Debug / Release)
  CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-2022

    steps:
      -  name: Checkout
         uses: actions/checkout@v4
      -  name: Add MSBuild to PATH
         uses: microsoft/setup-msbuild@v2
         with:
           msbuild-architecture: x64
      - name: Build
        run: |
          msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
